Repository falcosecurity/driverkit, pull requests merged in 2020-03, with the labels that each got.

#12 docs: update documentation for supported distributions
  README.md
  pkg/modulebuilder/builder/ubuntu.go
  pkg/modulebuilder/builder/vanilla.go
Labels: approved, area/docs, dco-signoff: yes, kind/documentation, lgtm, size/M

#20 Changed non-existant parameter -o to --output-module in documentation
  README.md
Labels: approved, area/docs, dco-signoff: yes, kind/documentation, lgtm, size/XS

#27 fix: docker image dependencies
  .circleci/config.yml
Labels: approved, area/build, dco-signoff: yes, kind/bug, lgtm, size/XS

#28 fix: ci image dependencies
  .circleci/config.yml
  Makefile
Labels: approved, area/build, dco-signoff: yes, kind/bug, lgtm, size/XS

#29 fix: image branch name
  .circleci/config.yml
Labels: approved, area/build, dco-signoff: yes, kind/bug, lgtm, size/XS

#30 fix: disable test packages filter
  Makefile
Labels: approved, area/build, dco-signoff: yes, kind/bug, lgtm, size/XS

#31 fix: remove unneded dependencies
  build/driverkit.Dockerfile
Labels: approved, area/build, dco-signoff: yes, kind/cleanup, kind/feature, lgtm, size/XS

#32 fix: pull image in docker builder
  pkg/driverbuilder/docker.go
Labels: approved, area/pkg, dco-signoff: yes, kind/feature, lgtm, size/XS

#36 update(pkg/driverbuilder): add new stream releases to look for
  pkg/driverbuilder/builder/centos.go
Labels: approved, area/pkg, dco-signoff: yes, kind/feature, lgtm, size/XS
