Repository falcosecurity/driverkit, pull requests merged in 2022-06, with the labels that each got.

#148 fix(build): fixed circleci config: cimg/base uses ubuntu and not alpine.
  .circleci/config.yml
Labels: kind/bug, area/build, dco-signoff: yes, approved, lgtm, size/XS

#149 update(build): use custom buildx builder with docker-container driver.
  Makefile
Labels: kind/bug, area/build, dco-signoff: yes, approved, lgtm, size/S

#150 fix(ci): fixed docker buildx usage.
  .circleci/config.yml
  Makefile
Labels: kind/bug, area/build, dco-signoff: yes, approved, lgtm, size/S

#151 fix(build): fix arm64 support on alpine (that is used by official docker image)
  .goreleaser.yml
  Makefile
Labels: kind/bug, area/build, dco-signoff: yes, approved, lgtm, size/XS

#131 Add builder for Flatcar
  README.md
  build/builder.Dockerfile
  cmd/testdata/completion-targets.txt
  pkg/driverbuilder/builder/flatcar.go
Labels: kind/feature, area/build, dco-signoff: yes, approved, lgtm, size/L

#156 fix(ci): fixed push latest images target.
  Makefile
Labels: kind/bug, area/build, dco-signoff: yes, approved, lgtm, size/XS

#157 fix(build): disable cgo.
  Makefile
Labels: kind/bug, area/build, dco-signoff: yes, approved, lgtm, size/XS

#159 Fix CGO_ENABLED for AmazonLinux2 drivers by detecting architecture type
  go.mod
  go.sum
  pkg/driverbuilder/builder/amazonlinux.go
Labels: kind/bug, area/build, dco-signoff: yes, approved, lgtm, size/M

#162 chore(build): dropped sqlite_tags and consequently empty GOTAGS.
  Makefile
Labels: kind/cleanup, area/build, dco-signoff: yes, approved, lgtm, size/S

#167 fix(pkg): stopping a stopped container is not an error.
  pkg/driverbuilder/docker.go
Labels: kind/bug, area/pkg, dco-signoff: yes, approved, lgtm, size/XS

#166 new(pkg/builder): allow `kernelurls` relative urls.
  pkg/driverbuilder/builder/builders.go
Labels: kind/bug, area/pkg, dco-signoff: yes, approved, lgtm, size/S

#168 new(pkg): drop requirements of `kernel` package for amazonlinux2 builder
  pkg/driverbuilder/builder/amazonlinux.go
Labels: kind/cleanup, area/pkg, dco-signoff: yes, approved, lgtm, size/M

#171 Use gcc-10 when building ubuntu kernels >= 5.13.0
  pkg/driverbuilder/builder/ubuntu.go
Labels: kind/bug, area/pkg, dco-signoff: yes, approved, lgtm, size/XS

#172 Fix CI failure
  pkg/driverbuilder/builder/ubuntu.go
Labels: kind/bug, dco-signoff: yes, approved, lgtm, size/XS

#174 fix: builder container stop, when already stopped
  Makefile
  pkg/driverbuilder/docker.go
Labels: kind/bug, area/pkg, dco-signoff: yes, approved, lgtm, size/XS

#175 fix(pkg): hopefully fix invalid gzip header error when downloading files from builder container
  go.mod
  go.sum
  pkg/driverbuilder/docker.go
Labels: kind/bug, area/pkg, dco-signoff: yes, approved, lgtm, size/M

#176 fix(goreleaser): drop GOTAGS support, after #162.
  .goreleaser.yml
Labels: kind/cleanup, area/build, dco-signoff: yes, approved, lgtm, size/XS

#177 chore(ci): store_artifacts on circleci for each build
  .circleci/config.yml
Labels: kind/feature, area/build, dco-signoff: yes, approved, lgtm, size/XS
