Repository falcosecurity/driverkit, pull requests merged in 2022-07, with the labels that each got.

#178 fix(test): fixed arm64 tests: eBPF probe requirement is now kernel >= 4.17
  test/aarch64/configs/ubuntu.yaml
  test/aarch64/configs/ubuntu_aws.yaml
Labels: kind/bug, area/tests, dco-signoff: yes, approved, lgtm, size/XS

#183 new(builder): added an archlinux builder.
  cmd/testdata/completion-targets.txt
  pkg/driverbuilder/builder/archlinux.go
  pkg/driverbuilder/builder/templates/archlinux.sh
Labels: kind/feature, area/pkg, dco-signoff: yes, approved, lgtm, size/L

#185 adjust ubuntu gcc versions
  pkg/driverbuilder/builder/ubuntu.go
Labels: kind/feature, area/pkg, dco-signoff: yes, approved, lgtm, size/XS

#181 update(docs): add me to owners.
  OWNERS
Labels: kind/documentation, area/docs, dco-signoff: yes, approved, lgtm, size/XS

#188 update(OWNERS): move inactive approvers to emeritus_approvers
  OWNERS
Labels: kind/documentation, dco-signoff: yes, approved, lgtm, size/XS

#190 update(docs): add minikube example configuration file
  README.md
Labels: kind/documentation, area/docs, dco-signoff: yes, approved, lgtm, size/S
