Repository falcosecurity/driverkit, pull requests merged in 2023-06, with the labels that each got.

#277 Fb update rhel9 example
  Example_configs.md
Labels: kind/documentation, area/docs, dco-signoff: yes, approved, lgtm, size/S

#278 fixed typos and improved RHEL9 builder image explanation
  Example_configs.md
Labels: kind/documentation, area/docs, dco-signoff: yes, approved, lgtm, size/XS

#279 fix(pkg): fixed mainline kernel URLs.
  pkg/driverbuilder/builder/templates/vanilla.sh
  pkg/driverbuilder/builder/vanilla.go
Labels: kind/bug, area/pkg, dco-signoff: yes, approved, lgtm, size/XS

#281 docs(README.md): add scope and status badges
  README.md
Labels: kind/documentation, dco-signoff: yes, approved, lgtm, size/XS
