Repository falcosecurity/driverkit, pull requests merged in 2023-02, with the labels that each got.

#250 feat: support amazonlinux2 5.15.x kernel
  pkg/driverbuilder/builder/amazonlinux.go
Labels: kind/feature, area/pkg, dco-signoff: yes, approved, lgtm, size/XS

#253 fix(makefile): fixed images push: we don't need `docker manifest` anymore for builder images
  Makefile
Labels: kind/bug, area/build, dco-signoff: yes, approved, lgtm, size/S

#252 cleanup: removed `builderrepo` option pointing to my dockerhub.
  Makefile
Labels: kind/cleanup, area/tests, dco-signoff: yes, approved, lgtm, size/XS
